### ISSUE TITLE
SketchRuleWrapper 找不到

### ISSUE THREAD

**Issue by cjSound** [majun2232/vue3sketchRuler#2]
npm包里面没有导出这个组件吗

- lib
  - index.es.js
导出没看到  SketchRuleWrapper
```js
var SketchRule = /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render]]);
SketchRule.install = (app) => {
  app.component(SketchRule.name, SketchRule);
};
export { SketchRule, SketchRule as default };

```

**Comment by majun2232** [comment]
SketchRuleWrapper 是2x的功能呢,2x还在研究中,暂时还用不了哦, 有兴趣的话,一起研究,目前源码已经传到master分支, 稳定版在1x分支中




 
发件人： cjSound
发送时间： 2021-11-12 12:07
收件人： majun2232/vue3sketchRuler
抄送： Subscribed
主题： [majun2232/vue3sketchRuler] SketchRuleWrapper 找不到 (Issue #2)
npm包里面没有导出这个组件吗
lib 
index.es.js
导出没看到 SketchRuleWrapper
var SketchRule = /* @__PURE__ */ _export_sfc(_sfc_main, [["render", _sfc_render]]);
SketchRule.install = (app) => {
  app.component(SketchRule.name, SketchRule);
};
export { SketchRule, SketchRule as default };
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
